// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV0Dez40K0aDM0sAXzbCoB5qGJyw817Ms',
    appId: '1:78337863592:web:f0fa56bd6b52a30477379d',
    messagingSenderId: '78337863592',
    projectId: 'foodhub-local-32bcf',
    authDomain: 'foodhub-local-32bcf.firebaseapp.com',
    storageBucket: 'foodhub-local-32bcf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAWiMek9qmFtLpDmJ-Pm8zPlfPTim-Nn8',
    appId: '1:78337863592:android:3f8980c1cd8df6dc77379d',
    messagingSenderId: '78337863592',
    projectId: 'foodhub-local-32bcf',
    storageBucket: 'foodhub-local-32bcf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZzHHW4t0k4vm_1lPzB1MdGLVlXof_edY',
    appId: '1:78337863592:ios:23f52735463d1b2c77379d',
    messagingSenderId: '78337863592',
    projectId: 'foodhub-local-32bcf',
    storageBucket: 'foodhub-local-32bcf.firebasestorage.app',
    iosBundleId: 'com.example.foodhubLocal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZzHHW4t0k4vm_1lPzB1MdGLVlXof_edY',
    appId: '1:78337863592:ios:23f52735463d1b2c77379d',
    messagingSenderId: '78337863592',
    projectId: 'foodhub-local-32bcf',
    storageBucket: 'foodhub-local-32bcf.firebasestorage.app',
    iosBundleId: 'com.example.foodhubLocal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAV0Dez40K0aDM0sAXzbCoB5qGJyw817Ms',
    appId: '1:78337863592:web:c8836b8707e5c41977379d',
    messagingSenderId: '78337863592',
    projectId: 'foodhub-local-32bcf',
    authDomain: 'foodhub-local-32bcf.firebaseapp.com',
    storageBucket: 'foodhub-local-32bcf.firebasestorage.app',
  );
}
